### ISSUE TITLE
Using libedit instead of readline

### ISSUE THREAD

**Issue by mikegriffin** [iuscommunity-pkg/mariadb101u#1]
I noticed that the mariadb101u-server-10.1.12-1.ius.centos7.x86_64 packages use libedit for the client (like Fedora), instead of readline (like the IUS 10.0 packages and the stock MariaDB packages on centos 7)

I wonder if you would consider reverting this Fedora upstream change, or if other IUS users have opinions.

There may be license issues I am not fully aware of but I do see that Percona Server recently transitioned back to readline in client 5.6.24

**Comment by carlwgeorge** [comment]
Thanks @mikegriffin for bringing this up.

Generally we try to align with Fedora when building our packages (we even fork our spec files from Fedora spec files).  However, IUS by nature has to diverge from Fedora in order to meet our goals of building for RHEL and to convert the package into [safe replacement packages](https://ius.io/SafeRepo/#safe-replacement-package).  This could be a case where it makes sense to use the RHEL approach (readline) instead of the Fedora approach (libedit).

More background on the Fedora change and the possible license issues can be found [here](https://bugzilla.redhat.com/show_bug.cgi?id=1079637).  I'm going to research this a bit more and allow some time for other users to provide feedback here.

**Comment by carlwgeorge** [comment]
Another consideration is that using libedit 3.1 on Fedora may make sense for their packages, but in EL7 we are limited to libedit 3.0.

**Comment by carlwgeorge** [comment]
- https://bugzilla.redhat.com/show_bug.cgi?id=1079637
- https://bugzilla.redhat.com/show_bug.cgi?id=1201988
- https://bugzilla.redhat.com/show_bug.cgi?id=1187469
- https://bugzilla.redhat.com/show_bug.cgi?id=1180403
- https://bugzilla.redhat.com/show_bug.cgi?id=1202022
- https://mariadb.atlassian.net/browse/MDEV-7777

**Comment by carlwgeorge** [comment]
> A package has multiple binaries, some of them are GPLv2, some are GPLv3, and some are MIT licensed. In this case, you do need to list all of the individual licenses of the compiled binaries in the License tag, so it should read: License: GPLv2 and GPLv3 and MIT

https://fedoraproject.org/wiki/Licensing:FAQ?rd=Licensing/FAQ#How_should_I_handle_multiple_licensing_situations.3F

Based on that, licensing doesn't stop us from making this change.

**Comment by b-harper** [comment]
Hey @mikegriffin,

I got some updated packages built with readline support.  Those packages will be hitting the testing repositories after tonight's automation run.  Let us know if they have the features you are looking for.

**Comment by b-harper** [comment]
Hey @mikegriffin,

I am going to delay pushing the test packages with readline support, so we can get a fix out for #2.   We will get these packages into the testing repositories early next week.

**Comment by b-harper** [comment]
Now that #2 has been address, mariadb101u 10.1.13-3 packages will be hitting the testing repositories after tonight's automation run.    Let us know if they have the features you are looking for.

**Comment by b-harper** [comment]
@mikegriffin reached out over other means and confirmed this is the functionally he was looking for.   We will work on getting some 1:10.1.14-2.ius packages built with this feature.

**Comment by b-harper** [comment]
Packages with this feature have been released.
