### ISSUE TITLE
cracklib enabled by default but dict file blocked by selinux by default

### ISSUE THREAD

**Issue by robolmos** [iuscommunity-pkg/mariadb101u#5]
OS: CentOS 7.3

Installed packages:

> mariadb101u-common-10.1.22-1.ius.centos7.x86_64
> mariadb101u-config-10.1.22-1.ius.centos7.x86_64
> mariadb101u-libs-10.1.22-1.ius.centos7.x86_64
> mariadb101u-errmsg-10.1.22-1.ius.centos7.x86_64
> mariadb101u-server-10.1.22-1.ius.centos7.x86_64
> mariadb101u-10.1.22-1.ius.centos7.x86_64

Enabled by default with config file:
> /etc/my.cnf.d/cracklib_password_check.cnf

Error in /var/log/mariadb/mariadb.log
> /usr/share/cracklib/pw_dict.pwd.gz: No such file or directory

Log in /var/log/audit/audit.log

> type=AVC msg=audit(1493247117.919:5269): avc:  denied  { read } for  pid=16797 comm="mysqld" name="pw_dict.pwd" dev="sda1" ino=16781617 scontex
t=system_u:system_r:mysqld_t:s0 tcontext=system_u:object_r:crack_db_t:s0 tclass=file

Due to inability to access dict file, when creating a user within mariadb it results in an error:

> ERROR 1819 (HY000): Your password does not satisfy the current

Additional info: https://mariadb.com/kb/en/mariadb/cracklib_password_check/#selinux

**Comment by b-harper** [comment]
Hey @robolmos,

Thanks for taking the time to pop into our IRC channel and create this issue.  The root of this issue is tied to cracklib and its default SELinux contexts.  Having our mariadb101u packages make a permission change to files owned by another package is not a good idea.  Until Red Hat makes a change, I see a few different options on how we could proceed:

1.  Keep cracklib support enabled by default.  For servers that are 'less secure' without SELinux, they will have 'better security' by having cracklib support enabled by default.  For 'more secure' servers with SELinux, they will have to make changes to get mariadb101u working. 
2.  Disable cracklib support by default.  All servers won't have cracklib by default, but servers with SELinux will work without any configuration changes.  All servers will need changes to enable cracklib support.

I think option 2 is better.  

@robolmos and others, I am interested in your thoughts on how we should proceed.

**Comment by robolmos** [comment]
@b-harper I think #2 is the better solution as well. My perspective is that with #2 it's also not "broken" by default but is still reasonably secure.

I think the cracklib config file could also have comments added to it about the SELinux issue for those that are curious to manually enable it.

**Comment by b-harper** [comment]
@robolmos,

Thanks for the feedback.  I'll work on commenting out the configuration and get some updated packages into the testing repositories.

**Comment by b-harper** [comment]
Updated packages have been built and are available in the test repositories.

**Comment by b-harper** [comment]
I noticed that the cracklib_password_check.cnf file was not set as %config(noreplace), so yum would overwrite any change made to that file.  Updated packages have been built and will hit the testing repositories during tonight's automation run.

**Comment by b-harper** [comment]
These changes will be included in the new 10.1.23 release which will be hitting the testing repositories during tonight's automation run.  Also, the updated 10.1.22 packages will be removed.

**Comment by b-harper** [comment]
The 10.1.23 packages will be hitting the stable repositories during tonight's automation run.
