### ISSUE TITLE
Provide ODBC connector

### ISSUE THREAD

**Issue by johnnybubonic** [iuscommunity-pkg/mariadb101u#9]
can you please also include the ODBC connector?

https://downloads.mariadb.com/Connectors/odbc/connector-odbc-3.0.3/

**Comment by johnnybubonic** [comment]
i should note that this is because the mysql ODBC connector used with a MySQL server gives bugs, at least with a socket connection (various segfaults, floating point exceptions, etc.)

**Comment by carlwgeorge** [comment]
Thanks for the suggestion.  That's a separate source tarball, and thus would be a different package.  That's how [Fedora does it](https://src.fedoraproject.org/rpms/mariadb-connector-odbc) as well.  Since it would be a new package, please create a [wishlist request](https://github.com/iuscommunity/wishlist/blob/master/CONTRIBUTING.md) and I'll take a closer look and what would be involved.

**Comment by johnnybubonic** [comment]
oops, apologies; didn't know there was a wishlist repo. should have checked. :)

thanks! filed.
